name: VPinataParty
version: '${project.version}'
main: github.vanes430.vpinataparty.VPinataParty
api-version: '1.20.6'
author: vanes430
description: A simple Pinata Party plugin for Paper.
folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false

permissions:
  vpinataparty.admin:
    description: Allows usage of all VPinataParty commands
    default: op